sudo: required
language: python
matrix:
    include:
        - python: 3.5
        - python: 2.7

install:
  - python setup.py install
  - pip install flake8 coveralls pytest-cov

# command to run tests
script:
  - flake8
  - py.test --cov tiling --cov-report term-missing


after_success:
  - coveralls
